// export const genres = [
//     "BLUES",
//     "COUNTRY",
//     "ELECTRONIC",
//     "FOLK",
//     "HIP HOP",
//     "JAZZ",
//     "POP",
//     "RYTHM AND BLUES",
//     "ROCK",
//     "METAL",
//     "PUNK",
//     "SAX",
//     "LOFI",
//     "RAP FR",
//     "TRAP",
//     "RAP US",
//     "DRILL",
//     "CLASSICAL",
//     "REGGAETON",
//     "BOOM BAP",
//     "DUBSTEP",
//     "SYNTHWAVE",
// ];

export const genres = [
    "COUNTRY",
    "ELECTRONIC",
    "FOLK",
    "JAZZ",
    "POP",
    "RYTHM AND BLUES",
    "ROCK",
    "METAL",
    "FUNK",
    "LOFI",
    "RAP US",
    "DRILL",
    "CLASSICAL",
    "SYNTHWAVE",
];
